services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      # access postgres outside:inside docker
      - 5432:5432
    volumes:
      # uses external storage (OS storage) for DB
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: